# Generated by Django 2.0.3 on 2018-04-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180407_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='following',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
