# Generated by Django 2.0.3 on 2018-03-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=100)),
                ('comment_text', models.TextField(max_length=250)),
                ('comment_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_likes', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('tweet', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloned.Tweet'),
        ),
    ]
