# Generated by Django 2.0.3 on 2018-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloned', '0002_auto_20180404_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
    ]
