# Generated by Django 2.0.3 on 2018-04-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloned', '0004_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Tweets'},
        ),
        migrations.AddField(
            model_name='tweet',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
