# Generated by Django 2.0.3 on 2018-04-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloned', '0005_auto_20180407_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Tweets'},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='date',
            new_name='date_created',
        ),
    ]
